import React from 'react'
import FaqElement from '../items/faqElement';

const unused = () => {

    const content = [
        {id: 1, question: "Can you help me?", answer: "Yes, we can! We strive to assist every individual and family with their specific needs to the best of our ability. Our team of dedicated volunteers works tirelessly to connect you with the necessary resources and support that are available. Then, we will continue to work with you until you are at the place you want to be.", hideList: "hideList"},
        {id: 2, question: "Who do you help?", answer: "We are here to help anyone facing hardships, including but not limited to those experiencing poverty, domestic violence, sexual abuse, physical and mental health concerns, discrimination, trauma, loss, and more. Our services are open to individuals of all backgrounds and circumstances, regardless of age, gender, race, or religion. No one should feel excluded, and we believe in fostering an inclusive, supportive, and healthy community for all.", hideList: "hideList"},
        {id: 3, question: "How can you help me?", answer: "We can help you by improving and providing access to a wide range of resources, including but not limited to food assistance, housing support, healthcare, mental health options, legal assistance, employment opportunities, education, and more. After you receive these options, our Client Advocates work with you to ensure these options are truly supporting you. If they are not, we will help you figure it out and determine next steps. You are not alone in this process. We are with you every step of the way. Our goal is to empower you to overcome challenges and improve your health and quality of life.", hideList: "hideList"},
        {id: 4, question: "How long does the process take?", answer: "Once you reach out to us, we will respond to your request within 24-48 hours. We understand the urgency of your situation, and our team will work promptly to address your needs and connect you with the appropriate resources as soon as possible.", hideList: "hideList"},
        {id: 5, question: "What happens after I reach out?", answer: "The next step is for you to schedule an intake with one of our Client Advocates, which takes anywhere from 20 minutes to 1 hour over the phone. Our Client Advocates will assist you in scheduling at a mutually convenient time. Afterward, we will work with you to determine a plan to improve your situation. This will involve deciding on a plan to communicate with your Client Advocate and utilize resources available. ", hideList: "hideList"},
        {id: 6, question: "How often can I meet with a Client Advocate?", answer: "As often as you need. We are here to support you and will work with you to determine a communication schedule that works with you, to ensure you feel supported and empowered.", hideList: "hideList"},
        {id: 7, question: "Who works on your services?", answer: "Our services are run by Volunteer Client Advocates who generously offer their time and expertise to help those in need. These compassionate individuals are committed to making a positive impact in the lives of others, and come from various backgrounds, including students pursuing degrees in Clinical and Counseling Psychology. They are not licensed but they are trained thoroughly in the skills they need to properly support you. In addition to our Volunteer Client Advocates, we also have experienced leaders with relevant Graduate degrees who oversee our clinical services. These professionals oversee and guide the student volunteers, ensuring that the support and assistance provided meet high standards of care and ethical practices.", answer2: "Our organization recognizes the importance of continuous growth and learning, for clients and volunteers! As such, volunteers are encouraged to participate in ongoing training and education to enhance their skills and stay informed about the latest developments in the field. We are proud to have such a dedicated team of volunteers and experienced professionals, all working together to make a positive impact on the lives of those we serve. Rest assured that our team is committed to providing empathetic and compassionate support while adhering to the highest standards of professionalism.", hideList: "hideList"},
        {id: 8, question: "I don't have consistent internet, what should I do?", answer: "Yes, we can! We strive to assist every individual and family with their specific needs to the best of our ability. Our team of dedicated volunteers works tirelessly to connect you with the necessary resources and support that are available. Then, we will continue to work with you until you are at the place you want to be.", oL1: "Text or call us: If you have access to a phone, you can reach out to our phone number (347-692-0011). Our friendly Client Advocates will be ready to assist you with your needs and provide information about available resources.", oL2: "Utilize Public Internet Access Points: NYC is filled with public places with free internet access, such as libraries, community centers, and cafes. Check your local neighborhood for available options and use these spaces to contact us.", oL3: "Request Information by Mail: If you prefer to receive information through traditional mail, please let us know, and we will do our best to send relevant resources and support materials to your provided address. However, it will be more difficult to work with you and follow up on the effectiveness of these resources.", answer2: "Our organization recognizes the importance of continuous growth and learning, for clients and volunteers! As such, volunteers are encouraged to participate in ongoing training and education to enhance their skills and stay informed about the latest developments in the field. We are proud to have such a dedicated team of volunteers and experienced professionals, all working together to make a positive impact on the lives of those we serve. Rest assured that our team is committed to providing empathetic and compassionate support while adhering to the highest standards of professionalism."},
        {id: 9, question: "Why does my call always go to voicemail?", answer: "This is intentional! As a growing organization, currently we do not the resources to monitor an active phone-line. The good news is this is changing very soon.", answer2: "Regardless, we assure you that we prioritize listening to voicemails and addressing each inquiry thoroughly. Therefore, when you call, please leave a detailed message, including your name, contact information, and the best time to call you back. Our team will make every effort to get back to you as soon as possible, during the time you requested, and within 24-48 hours.", answer3: "Your patience and understanding are greatly appreciated as we continue to grow and strive to improve our services.", hideList: "hideList"},
        {id: 10, question: "Can I use The Open Space? If so, how often?", answer: "Absolutely! We encourage you to utilize The Open Space as much as you need. The Open Space is a dedicated area where you can receive free and confidential mental health support and information from one of our Client Advocates. It is designed to be a safe and welcoming space for you to vent and have an empathetic ear.", hideList: "hideList"},
        {id: 11, question: "The Open Space is great, but I need a licensed mental health professional. Do you provide that?", answer: "We hear you. Unfortunately, mental healthcare access is a big problem right now, one we are actively working on improving, which is why we launched The Open Space. While The Open Space is a valuable resource, it currently does not include licensed mental health professionals. Our goal is to provide access to licensed providers in the future through The Open Space. In the meantime, your Client Advocate can assist you in finding a licensed mental health professional who can best address your specific needs and concerns.", hideList: "hideList"},
        {id: 12, question: "Can I apply for Food First?", answer: "Yes, you can apply for Food First if you are an active client of ours (i.e., your intake is complete and you are actively working with your assigned Client Advocate). However, it's important to note that applications are reviewed on a case-by-case basis. Submitting an application does not guarantee you will receive goods, as availability may be limited. Rest assured, we do our best to help as many clients as possible through Food First.", hideList: "hideList"},
        {id: 13, question: "Is there a cost for using your services?", answer: "No, our services are completely free of charge! We are a non-profit organization dedicated to helping individuals and families in need. Our support is provided at no cost!", hideList: "hideList"},
        {id: 14, question: "Can you just purchase me groceries or other supplies through Food First?", answer: "Unfortunately, it is not that simple. We are a growing, start-up organization and rely on limited funding. There are times when our supporters donate items in-kind, but this is not always the case and is not guaranteed. As a result, support for our Food First Program is inconsistent. We do our best to consider every request given and make decisions based on need. Despite this, we are committed to making sure you have food, essential supplies, and the resources you need, and we will help you obtain that, even if we cannot purchase them for you at this time.", hideList: "hideList"},
        {id: 15, question: "Are my personal details and information safe with you?", answer: "Absolutely. We take the privacy and security of your personal information seriously. Any information you share with us will be treated confidentially and used solely for the purpose of providing you with appropriate assistance. We adhere to strict data protection protocols to safeguard your data.", hideList: "hideList"},
        {id: 16, question: "Are your services available in multiple languages?", answer: "We strive to be inclusive and accessible to individuals from diverse linguistic backgrounds. While our primary language of communication is English. We may have volunteer Client Advocate who is proficient in other languages. If you prefer assistance in a specific language, please let us know, and we will do our best to accommodate your request.", hideList: "hideList"},
        {id: 17, question: "How can I refer someone else in need to your services?", answer: "If you know someone who could benefit from our services, you can refer them to us by providing them with our contact information or directing them to our website. Alternatively, you can inform our team directly, and we will reach out to the person in need to offer our support.", hideList: "hideList"},
        {id: 18, question: "Can I access your services if I live outside New York City?", answer: "Of course! While our services primarily focus on assisting individuals within NYC, we recognize that hardship impacts people in various regions and cities. If you reside outside the NYC area, please still feel free to reach out to us. Our team will do our best to connect you with relevant resources or refer you to organizations that may be able to assist you in your area.", hideList: "hideList"},
        {id: 19, question: "What happens if I reach out on a holiday, overnight, or the weekend?", answer: "We understand that seeking assistance may be necessary at any time, including holidays, overnight, or on weekends. To ensure you receive the support you need, we have dedicated Client Advocates available during extended hours, including weekends, and until 8pm EST on most weeknights. Rest assured that if you contact us during these times, we are committed to responding to your inquiry within 24-48 hours, regardless of holidays or weekends. Our team understands the importance of timely assistance and will do their best to promptly address your needs.", hideList: "hideList"},
        {id: 20, question: "What should I do if I need immediate assistance or it's an emergency?", answer: "If you require immediate assistance or are facing an emergency situation, please dial 911 or your local emergency helpline. While we strive to respond promptly, we are not able to address urgent matters directly and we are not an emergency service provider.", hideList: "hideList"},
    ] 
    return(
        <div>
            <div className="simpleFlex">
                <div className="maxWidth width80Per">
                <div className="ffMedium marginTop20 bottomBorder padBottom30">Frequently asked questions</div>
                {content.map((value) => (
                    <FaqElement content={{id: value.id, question: value.question, answer: value.answer, answer2: value.answer2, answer3: value.answer3, oL1: value.oL1, oL2: value.oL2, oL3: value.oL3, hideList: value.hideList}}/>
                ))}
                
                <div className="faqEndingStatement">Thank you. If you have any additional questions or need further assistance, please don't hesitate to contact us. We are here to support you on your journey to a brighter future!
                </div>
                </div>
            </div>
        </div>
    )
}

export default unused;